# Generated by Django 3.1.7 on 2021-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='album',
            name='artworks',
            field=models.ManyToManyField(blank=True, to='portfolio.Artwork'),
        ),
    ]
