# Generated by Django 3.1.7 on 2021-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210318_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256),
        ),
    ]
