# Generated by Django 3.1.7 on 2021-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210318_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='year_completed',
            field=models.IntegerField(blank=True, default=2021),
        ),
    ]
