# Generated by Django 3.1.7 on 2021-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210318_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='albums',
            field=models.ManyToManyField(blank=True, to='portfolio.Album'),
        ),
    ]
